# Generated by Django 4.2.6 on 2023-12-18 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallePeligrosas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=40)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=40)),
                ('descripcion', models.TextField()),
                ('nivelPeligro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTec.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTec.cliente')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTec.comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=18)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=18)),
                ('descripcion', models.TextField()),
                ('tipoIncidente', models.CharField(max_length=80)),
                ('nivelPeligro', models.CharField(max_length=80)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=9)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTec.cliente')),
            ],
        ),
    ]
