# Generated by Django 4.2.6 on 2023-12-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTec', '0002_rename_name_user_nombresapellidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nombresApellidos',
            new_name='nomape',
        ),
    ]
