# Generated by Django 4.2.6 on 2023-12-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTec', '0003_rename_nombresapellidos_user_nomape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nomape',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
