# Generated by Django 4.2.6 on 2023-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTec', '0004_alter_user_nomape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
