# Generated by Django 4.2.6 on 2023-12-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTec', '0005_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentes',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTec.cliente'),
        ),
    ]
