# Generated by Django 4.2.6 on 2023-12-11 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTec', '0006_alter_incidentes_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='idCalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTec.cliente'),
        ),
    ]
