# Generated by Django 4.2.6 on 2023-12-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTec', '0007_alter_comentario_idcalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='idCalle',
            new_name='idcliente',
        ),
    ]
