# Generated by Django 4.2.6 on 2023-12-11 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTec', '0008_rename_idcalle_comentario_idcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTec.cliente')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTec.comentario')),
            ],
        ),
    ]
