# Generated by Django 4.2.6 on 2023-12-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTec', '0009_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calle',
        ),
        migrations.RemoveField(
            model_name='incidentes',
            name='aprobado',
        ),
        migrations.AddField(
            model_name='incidentes',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='incidentes',
            name='nivelPeligro',
            field=models.CharField(blank=True, choices=[('B', 'Bajo'), ('M', 'Moderado'), ('A', 'Alto')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='incidentes',
            name='tipoIncidente',
            field=models.CharField(choices=[('I', 'Incendio'), ('F', 'Fuga de gas'), ('O', 'Accidente de tránsito')], default='I', max_length=1),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
